package com.yahorbarkouski.okdoc.openai.response

/**
 * Data class representing the response body of a chat completion.
 * Contains information about the chat completion including the ID of the completion,
 * the time the completion was created, the model used, and the list of chat choices generated.
 */
data class ChatResponse(
    val id: String,
    val created: Long,
    val model: String,
    val choices: List<Choice>,
)

/**
 * Data class representing a chat choice generated by the model.
 * Contains information about the index of the choice, the generated message, and the reason the chat stopped.
 */
data class Choice(
    val index: Int,
    val message: Message? = null,
    val finishReason: String?,
)

/**
 * Data class representing a message generated by the chat model.
 * Contains information about the role of the message (e.g. "user" or "bot") and the content of the message.
 */
data class Message(
    val role: String,
    val content: String,
)
